/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as DownloadRouteImport } from './routes/download'
import { Route as InfoRouteImport } from './routes/info'
import { Route as JoinRouteImport } from './routes/join'
import { Route as WindowsRouteImport } from './routes/windows'
import { Route as ApiInquiryRouteImport } from './routes/api/inquiry'
import { Route as ApiInquirySettingsRouteImport } from './routes/api/inquiry-settings'
import { Route as ApiLeadsRouteImport } from './routes/api/leads'
import { Route as ApiPrivateUnlockRouteImport } from './routes/api/private-unlock'
import { Route as ExperienceIndexRouteImport } from './routes/experience/index'
import { Route as ExperienceDestinationRouteImport } from './routes/experience/$destination'
import { Route as InfoIndexRouteImport } from './routes/info/index'
import { Route as InfoFaqRouteImport } from './routes/info/faq'
import { Route as InfoMembershipRouteImport } from './routes/info/membership'
import { Route as ApiDownloadMasterV1RouteImport } from './routes/api/download/master-v1'
import { Route as ApiDownloadPromoVideosRouteImport } from './routes/api/download/promo-videos'
import { Route as ApiDriveMainScreenRouteImport } from './routes/api/drive/main-screen'
import { Route as ApiTravelExperienceDestinationsRouteImport } from './routes/api/travel-experience/destinations'
import { Route as ApiTravelLifestyleStreamRouteImport } from './routes/api/travel-lifestyle/stream'
import { Route as ApiTravelLifestyleVideosRouteImport } from './routes/api/travel-lifestyle/videos'
import { Route as ExperienceDestinationIndexRouteImport } from './routes/experience/$destination/index'
import { Route as ExperienceDestinationStoryRouteImport } from './routes/experience/$destination/$story'
import { Route as ApiDriveFileFileIdRouteImport } from './routes/api/drive/file/$fileId'
import { Route as ApiDriveMainScreenImageRouteImport } from './routes/api/drive/main-screen/image'
import { Route as ApiDriveMenuMenuIdRouteImport } from './routes/api/drive/menu/$menuId'
import { Route as ApiDriveWindowWindowIdRouteImport } from './routes/api/drive/window/$windowId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadRoute = DownloadRouteImport.update({
  id: '/download',
  path: '/download',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoRoute = InfoRouteImport.update({
  id: '/info',
  path: '/info',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const WindowsRoute = WindowsRouteImport.update({
  id: '/windows',
  path: '/windows',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInquiryRoute = ApiInquiryRouteImport.update({
  id: '/api/inquiry',
  path: '/api/inquiry',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiInquirySettingsRoute = ApiInquirySettingsRouteImport.update({
  id: '/api/inquiry-settings',
  path: '/api/inquiry-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLeadsRoute = ApiLeadsRouteImport.update({
  id: '/api/leads',
  path: '/api/leads',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPrivateUnlockRoute = ApiPrivateUnlockRouteImport.update({
  id: '/api/private-unlock',
  path: '/api/private-unlock',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceIndexRoute = ExperienceIndexRouteImport.update({
  id: '/experience/',
  path: '/experience/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExperienceDestinationRoute = ExperienceDestinationRouteImport.update({
  id: '/experience/$destination',
  path: '/experience/$destination',
  getParentRoute: () => rootRouteImport,
} as any)
const InfoIndexRoute = InfoIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => InfoRoute,
} as any)
const InfoFaqRoute = InfoFaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => InfoRoute,
} as any)
const InfoMembershipRoute = InfoMembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => InfoRoute,
} as any)
const ApiDownloadMasterV1Route = ApiDownloadMasterV1RouteImport.update({
  id: '/api/download/master-v1',
  path: '/api/download/master-v1',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDownloadPromoVideosRoute = ApiDownloadPromoVideosRouteImport.update({
  id: '/api/download/promo-videos',
  path: '/api/download/promo-videos',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveMainScreenRoute = ApiDriveMainScreenRouteImport.update({
  id: '/api/drive/main-screen',
  path: '/api/drive/main-screen',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTravelExperienceDestinationsRoute =
  ApiTravelExperienceDestinationsRouteImport.update({
    id: '/api/travel-experience/destinations',
    path: '/api/travel-experience/destinations',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTravelLifestyleStreamRoute =
  ApiTravelLifestyleStreamRouteImport.update({
    id: '/api/travel-lifestyle/stream',
    path: '/api/travel-lifestyle/stream',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTravelLifestyleVideosRoute =
  ApiTravelLifestyleVideosRouteImport.update({
    id: '/api/travel-lifestyle/videos',
    path: '/api/travel-lifestyle/videos',
    getParentRoute: () => rootRouteImport,
  } as any)
const ExperienceDestinationIndexRoute =
  ExperienceDestinationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => ExperienceDestinationRoute,
  } as any)
const ExperienceDestinationStoryRoute =
  ExperienceDestinationStoryRouteImport.update({
    id: '/$story',
    path: '/$story',
    getParentRoute: () => ExperienceDestinationRoute,
  } as any)
const ApiDriveFileFileIdRoute = ApiDriveFileFileIdRouteImport.update({
  id: '/api/drive/file/$fileId',
  path: '/api/drive/file/$fileId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveMainScreenImageRoute = ApiDriveMainScreenImageRouteImport.update({
  id: '/image',
  path: '/image',
  getParentRoute: () => ApiDriveMainScreenRoute,
} as any)
const ApiDriveMenuMenuIdRoute = ApiDriveMenuMenuIdRouteImport.update({
  id: '/api/drive/menu/$menuId',
  path: '/api/drive/menu/$menuId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDriveWindowWindowIdRoute = ApiDriveWindowWindowIdRouteImport.update({
  id: '/api/drive/window/$windowId',
  path: '/api/drive/window/$windowId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/download': typeof DownloadRoute
  '/info': typeof InfoRouteWithChildren
  '/join': typeof JoinRoute
  '/windows': typeof WindowsRoute
  '/api/inquiry': typeof ApiInquiryRoute
  '/api/inquiry-settings': typeof ApiInquirySettingsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/private-unlock': typeof ApiPrivateUnlockRoute
  '/experience/$destination': typeof ExperienceDestinationRouteWithChildren
  '/info/faq': typeof InfoFaqRoute
  '/info/membership': typeof InfoMembershipRoute
  '/experience/': typeof ExperienceIndexRoute
  '/info/': typeof InfoIndexRoute
  '/api/download/master-v1': typeof ApiDownloadMasterV1Route
  '/api/download/promo-videos': typeof ApiDownloadPromoVideosRoute
  '/api/drive/main-screen': typeof ApiDriveMainScreenRouteWithChildren
  '/api/travel-experience/destinations': typeof ApiTravelExperienceDestinationsRoute
  '/api/travel-lifestyle/stream': typeof ApiTravelLifestyleStreamRoute
  '/api/travel-lifestyle/videos': typeof ApiTravelLifestyleVideosRoute
  '/experience/$destination/$story': typeof ExperienceDestinationStoryRoute
  '/experience/$destination/': typeof ExperienceDestinationIndexRoute
  '/api/drive/file/$fileId': typeof ApiDriveFileFileIdRoute
  '/api/drive/main-screen/image': typeof ApiDriveMainScreenImageRoute
  '/api/drive/menu/$menuId': typeof ApiDriveMenuMenuIdRoute
  '/api/drive/window/$windowId': typeof ApiDriveWindowWindowIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/download': typeof DownloadRoute
  '/join': typeof JoinRoute
  '/windows': typeof WindowsRoute
  '/api/inquiry': typeof ApiInquiryRoute
  '/api/inquiry-settings': typeof ApiInquirySettingsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/private-unlock': typeof ApiPrivateUnlockRoute
  '/info/faq': typeof InfoFaqRoute
  '/info/membership': typeof InfoMembershipRoute
  '/experience': typeof ExperienceIndexRoute
  '/info': typeof InfoIndexRoute
  '/api/download/master-v1': typeof ApiDownloadMasterV1Route
  '/api/download/promo-videos': typeof ApiDownloadPromoVideosRoute
  '/api/drive/main-screen': typeof ApiDriveMainScreenRouteWithChildren
  '/api/travel-experience/destinations': typeof ApiTravelExperienceDestinationsRoute
  '/api/travel-lifestyle/stream': typeof ApiTravelLifestyleStreamRoute
  '/api/travel-lifestyle/videos': typeof ApiTravelLifestyleVideosRoute
  '/experience/$destination/$story': typeof ExperienceDestinationStoryRoute
  '/experience/$destination': typeof ExperienceDestinationIndexRoute
  '/api/drive/file/$fileId': typeof ApiDriveFileFileIdRoute
  '/api/drive/main-screen/image': typeof ApiDriveMainScreenImageRoute
  '/api/drive/menu/$menuId': typeof ApiDriveMenuMenuIdRoute
  '/api/drive/window/$windowId': typeof ApiDriveWindowWindowIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/download': typeof DownloadRoute
  '/info': typeof InfoRouteWithChildren
  '/join': typeof JoinRoute
  '/windows': typeof WindowsRoute
  '/api/inquiry': typeof ApiInquiryRoute
  '/api/inquiry-settings': typeof ApiInquirySettingsRoute
  '/api/leads': typeof ApiLeadsRoute
  '/api/private-unlock': typeof ApiPrivateUnlockRoute
  '/experience/$destination': typeof ExperienceDestinationRouteWithChildren
  '/info/faq': typeof InfoFaqRoute
  '/info/membership': typeof InfoMembershipRoute
  '/experience/': typeof ExperienceIndexRoute
  '/info/': typeof InfoIndexRoute
  '/api/download/master-v1': typeof ApiDownloadMasterV1Route
  '/api/download/promo-videos': typeof ApiDownloadPromoVideosRoute
  '/api/drive/main-screen': typeof ApiDriveMainScreenRouteWithChildren
  '/api/travel-experience/destinations': typeof ApiTravelExperienceDestinationsRoute
  '/api/travel-lifestyle/stream': typeof ApiTravelLifestyleStreamRoute
  '/api/travel-lifestyle/videos': typeof ApiTravelLifestyleVideosRoute
  '/experience/$destination/$story': typeof ExperienceDestinationStoryRoute
  '/experience/$destination/': typeof ExperienceDestinationIndexRoute
  '/api/drive/file/$fileId': typeof ApiDriveFileFileIdRoute
  '/api/drive/main-screen/image': typeof ApiDriveMainScreenImageRoute
  '/api/drive/menu/$menuId': typeof ApiDriveMenuMenuIdRoute
  '/api/drive/window/$windowId': typeof ApiDriveWindowWindowIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/download'
    | '/info'
    | '/join'
    | '/windows'
    | '/api/inquiry'
    | '/api/inquiry-settings'
    | '/api/leads'
    | '/api/private-unlock'
    | '/experience/$destination'
    | '/info/faq'
    | '/info/membership'
    | '/experience/'
    | '/info/'
    | '/api/download/master-v1'
    | '/api/download/promo-videos'
    | '/api/drive/main-screen'
    | '/api/travel-experience/destinations'
    | '/api/travel-lifestyle/stream'
    | '/api/travel-lifestyle/videos'
    | '/experience/$destination/$story'
    | '/experience/$destination/'
    | '/api/drive/file/$fileId'
    | '/api/drive/main-screen/image'
    | '/api/drive/menu/$menuId'
    | '/api/drive/window/$windowId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/download'
    | '/join'
    | '/windows'
    | '/api/inquiry'
    | '/api/inquiry-settings'
    | '/api/leads'
    | '/api/private-unlock'
    | '/info/faq'
    | '/info/membership'
    | '/experience'
    | '/info'
    | '/api/download/master-v1'
    | '/api/download/promo-videos'
    | '/api/drive/main-screen'
    | '/api/travel-experience/destinations'
    | '/api/travel-lifestyle/stream'
    | '/api/travel-lifestyle/videos'
    | '/experience/$destination/$story'
    | '/experience/$destination'
    | '/api/drive/file/$fileId'
    | '/api/drive/main-screen/image'
    | '/api/drive/menu/$menuId'
    | '/api/drive/window/$windowId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/download'
    | '/info'
    | '/join'
    | '/windows'
    | '/api/inquiry'
    | '/api/inquiry-settings'
    | '/api/leads'
    | '/api/private-unlock'
    | '/experience/$destination'
    | '/info/faq'
    | '/info/membership'
    | '/experience/'
    | '/info/'
    | '/api/download/master-v1'
    | '/api/download/promo-videos'
    | '/api/drive/main-screen'
    | '/api/travel-experience/destinations'
    | '/api/travel-lifestyle/stream'
    | '/api/travel-lifestyle/videos'
    | '/experience/$destination/$story'
    | '/experience/$destination/'
    | '/api/drive/file/$fileId'
    | '/api/drive/main-screen/image'
    | '/api/drive/menu/$menuId'
    | '/api/drive/window/$windowId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  DownloadRoute: typeof DownloadRoute
  InfoRoute: typeof InfoRouteWithChildren
  JoinRoute: typeof JoinRoute
  WindowsRoute: typeof WindowsRoute
  ApiInquiryRoute: typeof ApiInquiryRoute
  ApiInquirySettingsRoute: typeof ApiInquirySettingsRoute
  ApiLeadsRoute: typeof ApiLeadsRoute
  ApiPrivateUnlockRoute: typeof ApiPrivateUnlockRoute
  ExperienceDestinationRoute: typeof ExperienceDestinationRouteWithChildren
  ExperienceIndexRoute: typeof ExperienceIndexRoute
  ApiDownloadMasterV1Route: typeof ApiDownloadMasterV1Route
  ApiDownloadPromoVideosRoute: typeof ApiDownloadPromoVideosRoute
  ApiDriveMainScreenRoute: typeof ApiDriveMainScreenRouteWithChildren
  ApiTravelExperienceDestinationsRoute: typeof ApiTravelExperienceDestinationsRoute
  ApiTravelLifestyleStreamRoute: typeof ApiTravelLifestyleStreamRoute
  ApiTravelLifestyleVideosRoute: typeof ApiTravelLifestyleVideosRoute
  ApiDriveFileFileIdRoute: typeof ApiDriveFileFileIdRoute
  ApiDriveMenuMenuIdRoute: typeof ApiDriveMenuMenuIdRoute
  ApiDriveWindowWindowIdRoute: typeof ApiDriveWindowWindowIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download': {
      id: '/download'
      path: '/download'
      fullPath: '/download'
      preLoaderRoute: typeof DownloadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info': {
      id: '/info'
      path: '/info'
      fullPath: '/info'
      preLoaderRoute: typeof InfoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/windows': {
      id: '/windows'
      path: '/windows'
      fullPath: '/windows'
      preLoaderRoute: typeof WindowsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inquiry': {
      id: '/api/inquiry'
      path: '/api/inquiry'
      fullPath: '/api/inquiry'
      preLoaderRoute: typeof ApiInquiryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/inquiry-settings': {
      id: '/api/inquiry-settings'
      path: '/api/inquiry-settings'
      fullPath: '/api/inquiry-settings'
      preLoaderRoute: typeof ApiInquirySettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/leads': {
      id: '/api/leads'
      path: '/api/leads'
      fullPath: '/api/leads'
      preLoaderRoute: typeof ApiLeadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/private-unlock': {
      id: '/api/private-unlock'
      path: '/api/private-unlock'
      fullPath: '/api/private-unlock'
      preLoaderRoute: typeof ApiPrivateUnlockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/': {
      id: '/experience/'
      path: '/experience'
      fullPath: '/experience/'
      preLoaderRoute: typeof ExperienceIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/$destination': {
      id: '/experience/$destination'
      path: '/experience/$destination'
      fullPath: '/experience/$destination'
      preLoaderRoute: typeof ExperienceDestinationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/info/': {
      id: '/info/'
      path: '/'
      fullPath: '/info/'
      preLoaderRoute: typeof InfoIndexRouteImport
      parentRoute: typeof InfoRoute
    }
    '/info/faq': {
      id: '/info/faq'
      path: '/faq'
      fullPath: '/info/faq'
      preLoaderRoute: typeof InfoFaqRouteImport
      parentRoute: typeof InfoRoute
    }
    '/info/membership': {
      id: '/info/membership'
      path: '/membership'
      fullPath: '/info/membership'
      preLoaderRoute: typeof InfoMembershipRouteImport
      parentRoute: typeof InfoRoute
    }
    '/api/download/master-v1': {
      id: '/api/download/master-v1'
      path: '/api/download/master-v1'
      fullPath: '/api/download/master-v1'
      preLoaderRoute: typeof ApiDownloadMasterV1RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/download/promo-videos': {
      id: '/api/download/promo-videos'
      path: '/api/download/promo-videos'
      fullPath: '/api/download/promo-videos'
      preLoaderRoute: typeof ApiDownloadPromoVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/main-screen': {
      id: '/api/drive/main-screen'
      path: '/api/drive/main-screen'
      fullPath: '/api/drive/main-screen'
      preLoaderRoute: typeof ApiDriveMainScreenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel-experience/destinations': {
      id: '/api/travel-experience/destinations'
      path: '/api/travel-experience/destinations'
      fullPath: '/api/travel-experience/destinations'
      preLoaderRoute: typeof ApiTravelExperienceDestinationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel-lifestyle/stream': {
      id: '/api/travel-lifestyle/stream'
      path: '/api/travel-lifestyle/stream'
      fullPath: '/api/travel-lifestyle/stream'
      preLoaderRoute: typeof ApiTravelLifestyleStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/travel-lifestyle/videos': {
      id: '/api/travel-lifestyle/videos'
      path: '/api/travel-lifestyle/videos'
      fullPath: '/api/travel-lifestyle/videos'
      preLoaderRoute: typeof ApiTravelLifestyleVideosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/experience/$destination/': {
      id: '/experience/$destination/'
      path: '/'
      fullPath: '/experience/$destination/'
      preLoaderRoute: typeof ExperienceDestinationIndexRouteImport
      parentRoute: typeof ExperienceDestinationRoute
    }
    '/experience/$destination/$story': {
      id: '/experience/$destination/$story'
      path: '/$story'
      fullPath: '/experience/$destination/$story'
      preLoaderRoute: typeof ExperienceDestinationStoryRouteImport
      parentRoute: typeof ExperienceDestinationRoute
    }
    '/api/drive/file/$fileId': {
      id: '/api/drive/file/$fileId'
      path: '/api/drive/file/$fileId'
      fullPath: '/api/drive/file/$fileId'
      preLoaderRoute: typeof ApiDriveFileFileIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/main-screen/image': {
      id: '/api/drive/main-screen/image'
      path: '/image'
      fullPath: '/api/drive/main-screen/image'
      preLoaderRoute: typeof ApiDriveMainScreenImageRouteImport
      parentRoute: typeof ApiDriveMainScreenRoute
    }
    '/api/drive/menu/$menuId': {
      id: '/api/drive/menu/$menuId'
      path: '/api/drive/menu/$menuId'
      fullPath: '/api/drive/menu/$menuId'
      preLoaderRoute: typeof ApiDriveMenuMenuIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/drive/window/$windowId': {
      id: '/api/drive/window/$windowId'
      path: '/api/drive/window/$windowId'
      fullPath: '/api/drive/window/$windowId'
      preLoaderRoute: typeof ApiDriveWindowWindowIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface InfoRouteChildren {
  InfoFaqRoute: typeof InfoFaqRoute
  InfoMembershipRoute: typeof InfoMembershipRoute
  InfoIndexRoute: typeof InfoIndexRoute
}

const InfoRouteChildren: InfoRouteChildren = {
  InfoFaqRoute: InfoFaqRoute,
  InfoMembershipRoute: InfoMembershipRoute,
  InfoIndexRoute: InfoIndexRoute,
}

const InfoRouteWithChildren = InfoRoute._addFileChildren(InfoRouteChildren)

interface ExperienceDestinationRouteChildren {
  ExperienceDestinationStoryRoute: typeof ExperienceDestinationStoryRoute
  ExperienceDestinationIndexRoute: typeof ExperienceDestinationIndexRoute
}

const ExperienceDestinationRouteChildren: ExperienceDestinationRouteChildren = {
  ExperienceDestinationStoryRoute: ExperienceDestinationStoryRoute,
  ExperienceDestinationIndexRoute: ExperienceDestinationIndexRoute,
}

const ExperienceDestinationRouteWithChildren =
  ExperienceDestinationRoute._addFileChildren(
    ExperienceDestinationRouteChildren,
  )

interface ApiDriveMainScreenRouteChildren {
  ApiDriveMainScreenImageRoute: typeof ApiDriveMainScreenImageRoute
}

const ApiDriveMainScreenRouteChildren: ApiDriveMainScreenRouteChildren = {
  ApiDriveMainScreenImageRoute: ApiDriveMainScreenImageRoute,
}

const ApiDriveMainScreenRouteWithChildren =
  ApiDriveMainScreenRoute._addFileChildren(ApiDriveMainScreenRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DownloadRoute: DownloadRoute,
  InfoRoute: InfoRouteWithChildren,
  JoinRoute: JoinRoute,
  WindowsRoute: WindowsRoute,
  ApiInquiryRoute: ApiInquiryRoute,
  ApiInquirySettingsRoute: ApiInquirySettingsRoute,
  ApiLeadsRoute: ApiLeadsRoute,
  ApiPrivateUnlockRoute: ApiPrivateUnlockRoute,
  ExperienceDestinationRoute: ExperienceDestinationRouteWithChildren,
  ExperienceIndexRoute: ExperienceIndexRoute,
  ApiDownloadMasterV1Route: ApiDownloadMasterV1Route,
  ApiDownloadPromoVideosRoute: ApiDownloadPromoVideosRoute,
  ApiDriveMainScreenRoute: ApiDriveMainScreenRouteWithChildren,
  ApiTravelExperienceDestinationsRoute: ApiTravelExperienceDestinationsRoute,
  ApiTravelLifestyleStreamRoute: ApiTravelLifestyleStreamRoute,
  ApiTravelLifestyleVideosRoute: ApiTravelLifestyleVideosRoute,
  ApiDriveFileFileIdRoute: ApiDriveFileFileIdRoute,
  ApiDriveMenuMenuIdRoute: ApiDriveMenuMenuIdRoute,
  ApiDriveWindowWindowIdRoute: ApiDriveWindowWindowIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
